Create Recruiter models and migrations
redhat-beyond/SJMaster pull request #34
Opened 2021-11-16 18:55 UTC by benmenachem

Created the following recruiter models: Recruiter, Company.
Created migration files to initialize the models and registered the created models on the admin site

2021-11-16 19:23 UTC, guyy13 approved these changes
lgtm

2021-11-17 08:49 UTC, guy9050 commented on recruiter/migrations/0001_initial.py
> +                ('company_website_url', models.CharField(max_length=255)),
no need for `company_` prefix

2021-11-20 20:26 UTC, YarinBou approved these changes

2021-11-21 07:09 UTC, yaelerdr approved these changes

2021-11-21 07:32 UTC, eldaraharonson approved these changes

2021-11-21 07:49 UTC, ifireball requested changes

2021-11-21 07:49 UTC, ifireball commented on recruiter/models.py
> +    first_name = models.CharField(max_length=255)
Why do you need to separate the first and last names? Not all names have just 2 components, see similar comment I made on the Student model PR.

2021-11-21 11:34 UTC, ifireball approved these changes

2021-11-21 11:34 UTC, merged