Create new job creation form
redhat-beyond/SJMaster pull request #62
Opened 2021-12-10 14:08 UTC by benmenachem

Created a new job creation form: 

* As of now the access to the page will be directly through recruiter/create_new_job_form 
* Once we will have a recruiter profile page the access to the job creation form will be through the personal profile
* After the job is created the recruiter will be directed to a success page and from there he'll be able to go back to the job board. once the profile page will be ready he'll be able to go back to his profile as well. 
* In addition, I changed the created_date field in the job board application from a DateField to a DateTimeField. 
* Adding 2 screen shots of what the job creation form and the success page look like: 
<img width="1399" alt="Screen Shot 2021-12-10 at 3 52 50 PM" src="https://user-images.githubusercontent.com/92451459/145586559-d9fd9b83-667e-4d5e-a2f0-a31d645d57b0.png">

<img width="1399" alt="Screen Shot 2021-12-10 at 3 50 50 PM" src="https://user-images.githubusercontent.com/92451459/145586655-b41a308e-ee89-4a43-b88d-06be11686fae.png">

2021-12-11 13:14 UTC, eldaraharonson requested changes
The form looks very neat! However I feel like the Recruiter field and Date Created fields can be automatically filled in. The recruiter field will automatically be the i.d. of the recruiter that is currently logged in, and the date created field will automatically be date.today()

2021-12-11 13:18 UTC, benmenachem commented
> The form looks very neat! However I feel like the Recruiter field and Date Created fields can be automatically filled in. The recruiter field will automatically be the i.d. of the recruiter that is currently logged in, and the date created field will automatically be date.today()

I agree. I think that the fields that should be automatically filled in are company, recruiter and date. I'm trying  to do that right now.

2021-12-11 13:23 UTC, guyy13 commented
@benmenachem 
I think the company field should be filled in automatically as well, as a recruiter can only work for one company (as we implemented it) so obviously, they will post a job in the name of the company they work at.

2021-12-11 13:26 UTC, benmenachem commented
> @benmenachem
> I think the company field should be filled in automatically as well, as a recruiter can only work for one company (as we implemented it) so obviously, they will post a job in the name of the company they work at.

see my reply to eldar

2021-12-11 16:30 UTC, YarinBou commented
looking great ben!

2021-12-12 06:54 UTC, guyy13 commented
Ok I think I managed to get it down, you can remove the Company, Recruiter and Date Created fields from the form and then override the "form_valid" method with the following code in order to fill these fields automatically:
`    def form_valid(self, form):
        logged_recruiter = Recruiter.objects.get(user_id=self.request.user.id)
        form.instance.recruiter = logged_recruiter
        form.instance.company = logged_recruiter.company
        form.instance.date_created = date.today()
        return super(CreateNewJobForm, self).form_valid(form)`

Also, you might want to make sure that the user requesting to view the page is a Recruiter, you can do that by making the class inherit from the "UserPassesTestMixin" class, and defining the following method:
`    def test_func(self):
        return Recruiter.is_recruiter(self.request.user.id)`

After doing so you can remove the "<slug:pk>" part from the URL as it's no longer needed.

2021-12-12 07:36 UTC, benmenachem commented
> Ok I think I managed to get it down, you can remove the Company, Recruiter and Date Created fields from the form and then override the "form_valid" method with the following code in order to fill these fields automatically: `def form_valid(self, form): logged_recruiter = Recruiter.objects.get(user_id=self.request.user.id) form.instance.recruiter = logged_recruiter form.instance.company = logged_recruiter.company form.instance.date_created = date.today() return super(CreateNewJobForm, self).form_valid(form)`
> 
> Also, you might want to make sure that the user requesting to view the page is a Recruiter, you can do that by making the class inherit from the "UserPassesTestMixin" class, and defining the following method: `def test_func(self): return Recruiter.is_recruiter(self.request.user.id)`
> 
> After doing so you can remove the "slug:pk" part from the URL as it's no longer needed.
> 
> EDIT: I can't get the code to look right with the indentation so here's a screenshot just in case. ![image](https://user-images.githubusercontent.com/91069555/145703451-67c5f8f3-2811-42d6-9c9a-2c82801d6af1.png)

Thanks @guyy13. I added your code and it managed to work. The recruiter, company and date fields now would be automatically filled in and won't be seen to the recruiter while filling the form. adding updated pictures of what the form looks like to the PR description right now.

2021-12-12 08:15 UTC, YarinBou approved these changes

2021-12-12 10:09 UTC, eldaraharonson approved these changes

2021-12-12 12:35 UTC, guy9050 commented
please squash the commits

2021-12-12 16:40 UTC, benmenachem commented
> please squash the commits

@guy9050 Done

2021-12-13 09:37 UTC, merged