Adding links to recruiter's account settings & create new job form.
redhat-beyond/SJMaster pull request #67
Opened 2021-12-15 18:36 UTC by benmenachem

* Added links from navbar to the recruiter' account settings & create new job form 
* Added the major field to the create new job form

2021-12-15 18:39 UTC, guyy13 requested changes

2021-12-15 18:39 UTC, guyy13 commented on SJMaster/templates/base.html
> +                        <a class="nav-link" href="recruiter/create_new_job_form">Create a new job</a>
Maybe change it to "Create Job"?

2021-12-15 18:41 UTC, benmenachem commented on SJMaster/templates/base.html
> +                        <a class="nav-link" href="recruiter/create_new_job_form">Create a new job</a>
fine

2021-12-15 18:41 UTC, guyy13 approved these changes
lgtm

2021-12-15 18:42 UTC, guyy13 approved these changes

2021-12-15 22:25 UTC, yaelerdr approved these changes

2021-12-16 08:06 UTC, eldaraharonson approved these changes

2021-12-17 10:00 UTC, ifireball requested changes
No tests? Am I supposed to guess if this code does what you intended it to do?

2021-12-17 10:24 UTC, benmenachem commented
> No tests? Am I supposed to guess if this code does what you intended it to do?

I'll update the PR with tests later today

2021-12-17 15:38 UTC, benmenachem commented
> > No tests? Am I supposed to guess if this code does what you intended it to do?
> 
> @ifireball I wasn't really sure about the tests for this PR.
 I consulted with @guyy13 and we agreed that the entire logic of this PR relies on the is_student and is_recruiter model functions that already have tests. therefore I don't think there's anything test here as you instructed not to test the content of the html itself.

2021-12-17 16:18 UTC, benmenachem commented
> > No tests? Am I supposed to guess if this code does what you intended it to do?

 @ifireball I wasn't really sure about the tests for this PR. I consulted with @guyy13 and we agreed that the entire logic of this PR relies on the is_student and is_recruiter model functions that already have tests. therefore I don't think there's anything test here as you instructed not to test the content of the html itself.

2021-12-17 16:52 UTC, ifireball commented
This PR is not devoid of logic. I think we discussed how to move logic out of templates and into testable locations somewhere already.

Right now there is no test that gives you any form of verification that the right links are displayed under the right conditions.

2021-12-17 17:02 UTC, guyy13 commented
> This PR is not devoid of logic. I think we discussed how to move logic out of templates and into testable locations somewhere already.
> 
> Right now there is no test that gives you any form of verification that the right links are displayed under the right conditions.

We did discuss it and if I recall correctly you said we'd have to create separate views or even templates in order to move the logic out. Since this is a shared navigation bar across all of the pages I'm not sure how we would do that here. We could try to test the content of the HTML itself in order to check that the links are correct, but again as I recall you said to avoid it. Anyway I really don't understand why we need to test it, we test the context that we pass to the html, if we test that the correct links are showing up we basically test the if statement of Python.

2021-12-17 17:20 UTC, ifireball commented
A. Of course you need to test the 'if' statements those commonly get messed up as code is maintained over time.
B. We talked about having different included template files, not different views
C. There is at least one new context updating function in this MR that I don't see tests for either for itself or for the views that use it

2021-12-17 17:42 UTC, guyy13 commented
> A. Of course you need to test the 'if' statements those commonly get messed up as code is maintained over time.
> B. We talked about having different included template files, not different views
> C. There is at least one new context updating function in this MR that I don't see tests for either for itself or for the views that use it

Ok, we'll try to figure it out

2021-12-18 08:33 UTC, closed without merging